name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.14.0
  firebase_auth: 5.6.0
  http: ^1.1.0

  # UI PACKAGES
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1

  # NATIVE FUNCTIONALITY PACKAGES
  file_picker: ^10.2.0
  path_provider: ^2.1.3
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  video_player: ^2.8.6
  flutter_secure_storage: ^9.0.0 
  # Audio and API packages
  dio: ^5.4.3+1
  flutter_sound: ^9.3.0
  record: ^5.1.2
  speech_to_text: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Eira 0.1.png
    - assets/images/Eira 0.2.png
    - assets/images/Eira 1.png
    - assets/images/Eira.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Health.png"

dependency_overrides:
  record_linux: ^1.1.0
