// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
     apiKey: "AIzaSyCE3oVE6v35eJOWGRsjAioE7oXmDqeHfWM",
  authDomain: "eira-auth.firebaseapp.com",
  projectId: "eira-auth",
  storageBucket: "eira-auth.firebasestorage.app",
  messagingSenderId: "156078445635",
  appId: "1:156078445635:web:fe8d696841f581c1f130f6"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMgQWfyf9hDgaSfdrQcUbcK9W_Ajj8xU',
    appId: '1:156078445635:android:b54d7e07bf4a3bfaf130f6',
    messagingSenderId: '156078445635',
    projectId: 'eira-auth',
    storageBucket: 'eira-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCKl2P8UTIEljlz9GfD9pecrapoj-ToQ',
    appId: '1:156078445635:ios:779944f3eef2e435f130f6',
    messagingSenderId: '156078445635',
    projectId: 'eira-auth',
    storageBucket: 'eira-auth.firebasestorage.app',
    iosBundleId: 'bock.eira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkP6z1PcWxBxjRBbWcEC2bUjqqTrWkPv8',
    appId: '1:599590060410:ios:9307fa646bae1c1ab6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5a2rHT2TWK3CsrExJ48r0vken-5xsMc',
    appId: '1:599590060410:web:7e7e67760ab74c07b6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    authDomain: 'flutterapplication1-abdad.firebaseapp.com',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
  );
}
